#+TITLE:       Twine 2 Story and Proofing Format Documentation
#+AUTHOR:      Ashlynn Anderson
#+EMAIL:       ashlynn@pea.sh
#+DATE:        2020-01-05
#+LANGUAGE:    en

 | Status:   | In-Progress                                                     |
 | Location: | [[https://github.com/transitracer/twine-storyformat-documentation]] |
 | Version:  | 0.1.0                                                           |

* Motivation

For some time, there has been no such thing as documentation for the
Twine 2 story (and proofing) formats. This document's goal is to
change that.

Like many others, the author of this document was interested in
writing a Twine 2 story format and found that, in nearly every case,
documentation could only be found in the form of code.

This project has no timeline, as this is just a hobby for me and I
don't personally use Twine very frequently, but if you notice
something wrong or out-of-date please open up an Issue or, even
better, a Pull Request. As this is a documentation only project, it's
very simple on GitHub to open a Pull Request using only the web
interface, simply by hitting the pencil icon at the top right corner
of a file, so any contributions are very appreciated.

* Table of Contents

 + Part 1: Documentation
   1. [[chapter/01-introduction.org][Introduction]]
      - [[chapter/01-introduction.org#what-is-twine][What is Twine?]]
      - [[chapter/01-introduction.org#what-is-a-story-format][What is a story format?]]
      - [[chapter/01-introduction.org#what-is-the-difference-between-a-story-format-and-a-proofing-format][What is the difference between a story format and a proofing format?]]
   2. The Story Data Format
   3. Making Your Story Format Importable
 + Part 2: Cookbook
   1. TODO

* License

This documentation is released under [[https://creativecommons.org/licenses/by-sa/4.0/][CC-BY-SA 4.0]]. For the full terms
of the CC-BY-SA 4.0 license, see the [[LICENSE]] file.
